parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Core\EventSubscriber\KernelEventsSubscriber:
        tags: [kernel.event_subscriber]

    App\Service\Utils\QuotesSubscriber:
        arguments: { $senderAddress: 'foo@bar.com' }
        tags: [kernel.event_subscriber]

    App\Core\RequestToDTOConverter:
        tags: [request.param_converter]

    App\Service\QuotesService\QuotesService:
        arguments: ['%kernel.project_dir%/config/companylist.csv']
    
